/-
Entry point for the guide. [guide.sh](../../scripts/guide.sh) runs this with `--output`.
-/
import VersoManual
import CadenceGuide

open Verso.Genre.Manual

/-- The guide shares the rendered sources' presentation of Lean code, since
its model quotations are the same highlighted code: the site stylesheet
(plain comments set back from the code, their inline markup styled), the
comment-markup script, and the link table the script resolves the relative
links of quotations and embedded docstrings through
([site-comments.js](../site-comments.js)); the guide's own links are resolved
when it is rendered ([guide.sh](../../scripts/guide.sh)). The files are copied
to the guide's root, which every page's `<base href>` points at; the table is
generated by [docs.sh](../../scripts/docs.sh), which runs first. -/
def config : RenderConfig where
  extraFilesHtml := [
    ("docs/site-overrides.css", "site-overrides.css"),
    ("docs/site-comments.js", "site-comments.js"),
    (".lake/build/literate/site-links.js", "site-links.js")]
  extraHead := #[.text false
    "<link rel=\"stylesheet\" href=\"site-overrides.css\">\
     <script src=\"site-links.js\"></script>\
     <script src=\"site-comments.js\" defer></script>"]

def main := manualMain (%doc CadenceGuide) (config := config)
