#!/usr/bin/env bash
# Render the Lean sources as a browsable site for auditors, and publish the
# machine-derived trust boundary alongside them.
#
#   scripts/docs.sh [outdir]        # default outdir: site/
#
# What this produces, and why each piece is there:
#
#   index.html            an audit-oriented landing page — the three questions
#                         an auditor asks, each linked to where it is answered
#   trust-boundary.html   generated by scripts/TrustSurface.lean from the
#                         compiled environment: the axiom footprint of every
#                         end result, the (empty) list of axioms this
#                         development declares, and which module contracts
#                         have no instance
#   Cadence/*.html        every module's own prose, rendered — the long
#                         `/-! … -/` headers that carry the modelling
#                         rationale, with each declaration linked to its source
#
# The documentation generator is `doc-gen4`, pinned in lakefile.lean behind
# `-Kenv=dev` so it never enters a normal `lake build`. The first run is
# expensive: doc-gen4 analyses the whole import closure and emits HTML for it,
# so the site is ~400 MB of which this project is ~6 MB — the rest is Lean
# core, Batteries and the imported subset of Mathlib, kept so that a reviewer
# clicking through to a dependency's definition lands on a real page. Later
# runs are incremental: only modules whose hash changed are re-analysed.
#
# Requires the project to be built (`lake build`), since doc-gen4 reads the
# `.olean`s rather than re-elaborating the sources.
set -euo pipefail

cd "$(dirname "$0")/.."
OUT="${1:-site}"
DOC=".lake/build/doc"

echo "=== 1/4  building documentation (doc-gen4)"
# doc-gen4 panics, non-fatally and once per declaration, on anything without a
# source position — which is most of what Veil generates (state projections,
# enum instances). Those declarations are dropped from the output; the prose
# and the hand-written declarations render correctly. The noise is summarised
# rather than dumped, because at ~300 backtraces it buries real errors.
LOG="$(mktemp)"
trap 'rm -f "$LOG"' EXIT
if ! LEAN_NUM_THREADS="${LEAN_NUM_THREADS:-4}" lake -R -Kenv=dev build Cadence:docs \
      > "$LOG" 2>&1; then
  echo "--- doc-gen4 failed; last 40 lines:" >&2
  tail -40 "$LOG" >&2
  exit 1
fi
positionless=$(grep -c 'is a declaration without position' "$LOG" || true)
grep -vE 'is a declaration without position|^backtrace:|^[0-9]+ +doc-gen4|^[0-9]+ +lib(system|c)|WARNING: Failed to obtain information for:|^ *$' \
  "$LOG" | tail -20
echo "    (doc-gen4 skipped ${positionless} Veil-generated declarations that carry"
echo "     no source position; see docs/Documentation.md)"

if [ ! -d "$DOC" ]; then
  echo "error: doc-gen4 produced no output at $DOC" >&2
  exit 1
fi

echo "=== 2/4  deriving the trust boundary from the compiled environment"
# scratch.sh supplies the native plugins Lean needs for this project's modules.
bash scripts/scratch.sh scripts/TrustSurface.lean \
  | sed -n '/^<!DOCTYPE html>/,$p' > "$DOC/trust-boundary.html"
if [ ! -s "$DOC/trust-boundary.html" ]; then
  echo "error: TrustSurface.lean produced no page" >&2
  exit 1
fi
# A drifted axiom pin must fail the docs build, not be published quietly.
if grep -q 'UNEXPECTED' "$DOC/trust-boundary.html"; then
  echo "error: an end result carries an unexpected axiom - see trust-boundary.html" >&2
  exit 1
fi

echo "=== 3/4  writing the landing page"
cat > "$DOC/index.html" <<'LANDING'
<!DOCTYPE html><html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Cadence — auditing the formalization</title>
<link rel="stylesheet" href="style.css">
<style>
  body{max-width:62rem;margin:0 auto;padding:2rem 1.25rem;line-height:1.55}
  .q{margin:1.6rem 0;padding:1rem 1.2rem;border-left:3px solid #8886}
  .q h2{margin:.1rem 0 .5rem}
  code{font-size:.92em}
  ul{margin:.4rem 0}
  .note{opacity:.8;font-size:.94em}
</style></head><body>

<h1>Cadence — auditing the formalization</h1>

<p>This site renders the Lean sources of the machine-checked verification of
the Cadence BFT consensus protocol, together with a trust boundary derived
from the compiled development. It is written for a reviewer who wants to
check that the formalization says what the protocol says, and that what it
claims is actually proven.</p>

<p class="note">You do not need to read any proof. A theorem holds when Lean's
kernel accepts it, relative to the axioms it uses — so the audit surface is
the <em>statements</em>, the <em>model</em> they are about, and the
<em>axioms</em> they rest on. The three questions below are exactly those.</p>

<div class="q">
<h2>1. Is this the right protocol?</h2>
<p>Read the models. Each carries a header stating its scope, the abstractions
it takes deliberately, and how each of the paper's properties is covered.</p>
<ul>
  <li><a href="Cadence/Chorus.html">Chorus</a> — per-slot consensus (the largest model)</li>
  <li><a href="Cadence/Mvba.html">Mvba</a> — the leader-based MVBA instantiation</li>
  <li><a href="Cadence/Conductor.html">Conductor</a> — the window-based orchestrator</li>
  <li><a href="Cadence/Cadence.html">Cadence</a> — the pipelining glue</li>
  <li><a href="Cadence/FallbackReceipt.html">FallbackReceipt</a> — the fallback receipt/propose layer</li>
</ul>
</div>

<div class="q">
<h2>2. Are these the right properties?</h2>
<p>The paper's module specifications are stated as Lean type classes, and each
implementation is checked against them.</p>
<ul>
  <li><a href="Cadence/Interfaces.html">Interfaces</a> — every property of every paper module, as a class field</li>
  <li><a href="Cadence.html">Cadence (the audit root)</a> — every end result on one page, with its axiom pin</li>
</ul>
</div>

<div class="q">
<h2>3. Is it actually proven?</h2>
<p><a href="trust-boundary.html"><strong>The trust boundary</strong></a> —
generated from the compiled development, not written by hand: the axiom
footprint of every end result, the axioms this development declares (none),
which module contracts have no instance, and what no machine checks.</p>
</div>

<p class="note">Design rationale, the meta-assumption inventory and the paper
correspondence live in the repository's <code>docs/</code> directory; this
site renders the sources. Use the search box for a declaration by name.</p>

</body></html>
LANDING

echo "=== 4/4  staging the site into $OUT"
rm -rf "$OUT"
mkdir -p "$OUT"
# Copy everything doc-gen4 emitted, dependencies included, so that every
# cross-reference resolves. Only the modules actually imported are rendered,
# which is why this is a few hundred MB rather than the multi-gigabyte tree a
# full Mathlib render would produce.
cp -R "$DOC"/. "$OUT"/

echo
echo "=== site staged in $OUT ($(du -sh "$OUT" | cut -f1))"
echo "    open $OUT/index.html"
