#!/usr/bin/env bash
# Render the Lean sources as a browsable site for auditors, and publish the
# machine-derived trust boundary alongside them.
#
#   scripts/docs.sh [outdir]        # default outdir: site/
#
# What this produces, and why each piece is there:
#
#   index.html            an audit-oriented landing page — the three questions
#                         an auditor asks, each linked to where it is answered
#   trust-boundary.html   generated by scripts/TrustSurface.lean from the
#                         compiled environment: the axiom footprint of every
#                         end result, the (empty) list of axioms this
#                         development declares, and which module contracts
#                         have no instance
#   sources/              every module rendered in source order — the prose,
#                         the declarations it describes, and the code between
#                         them — by Verso's literate renderer, configured in
#                         `literate.toml`
#
# Requires the project to be built (`lake build`). The check below is a hard
# gate rather than a convenience: stage 2 runs with `VEIL_NO_VERIFY=1`, and an
# out-of-date olean rebuilt under that variable would be an unverified olean
# in the build tree. `--no-build` makes that impossible — if anything is
# stale, this script stops before setting the variable.
#
# Why this drives Verso's three binaries instead of `lake query :literateHtml`
# — which is the documented one-line way to do it — is explained at stage 2.
set -euo pipefail

cd "$(dirname "$0")/.."
REPO="$PWD"
OUT="${1:-site}"
WORK=".lake/build/literate"
VBIN=".lake/packages/verso/.lake/build/bin"

echo "=== 0/5  checking the project is built"
command -v jq > /dev/null || { echo "error: this script needs jq" >&2; exit 1; }
# Lake caches the elaborated lakefile and reuses it even when a `-K` option
# changes, so a workspace last configured without `-Kenv=dev` — the published
# image's, or any checkout after a plain `lake build` — does not know Verso
# exists, and every `-Kenv=dev` call below fails with "unknown package
# `verso`". Reconfigure once (`-R`); loading the workspace also clones Verso
# on first use. Builds nothing, so the gate below still sees the real state.
lake -R -Kenv=dev env true
if ! lake -Kenv=dev build --no-build Cadence > /dev/null 2>&1; then
  echo "error: the project is not up to date — run 'lake build' (or" >&2
  echo "       scripts/revalidate.sh) first; the site renders what was built." >&2
  exit 1
fi
mkdir -p "$WORK"
# Verso is pinned behind `-Kenv=dev`, so a normal `lake build` never sees it.
# Quiet on success, but lake reports a failing job's log on stdout, so keep it
# and show it on failure — "error: build failed" alone says nothing.
if ! LEAN_NUM_THREADS="${LEAN_NUM_THREADS:-4}" lake -Kenv=dev build \
       verso/verso-literate verso/verso-literate-plan verso/verso-literate-html \
       > "$WORK/verso-build.log" 2>&1; then
  cat "$WORK/verso-build.log" >&2
  echo "error: building Verso's literate renderer failed (log above)" >&2
  exit 1
fi

echo "=== 1/5  planning the site from literate.toml"
# Every module of the one library this package builds, in the
# "<library><tab><module>" form the planner reads.
find Cadence -name '*.lean' | sed 's#\.lean$##; s#/#.#g; s#^#Cadence\t#' \
  | sort > "$WORK/modules.txt"
printf 'Cadence\tCadence\n' >> "$WORK/modules.txt"
# The planner applies `targets`, `exclude` and the ordering keys, and prints
# the modules the site will contain, in site order.
lake -Kenv=dev env "$VBIN/verso-literate-plan" \
  "$WORK/modules.txt" "$WORK/plan.txt" literate.toml
echo "    $(grep -c . < "$WORK/plan.txt") of $(wc -l < "$WORK/modules.txt" | tr -d ' ') modules selected"

# Drop the proof states from a rendered module, in place.
#
# Verso records the goal at every tactic step and renders each one into the
# page. That is the wrong trade for this site twice over: an auditor is told
# they do not need to read a proof, and a goal over a forty-field state record
# is enormous — `Cadence.Mvba.Compose` came to **47 MB** from 360 lines of
# source, two thirds of the whole site, before this.
#
# A `tactics` node lists its states in `info`; emptying that and dropping the
# `goals` table removes them and nothing else. Measured on `Mvba.Compose`:
# 47 MB -> 0.32 MB, with every declaration, statement, docstring and comment
# still present (`mvbaSafety`, `mvba_of_temporal`, all 13 `theorem`s
# unchanged; only the 1 870 occurrences of `decided` *inside hypotheses* go).
#
# Idempotent, so a cached module is not re-stripped.
strip_proof_states() {
  local f="$1" tmp="$1.tmp"
  jq -c '.items.code |= with_entries(
           if (.value | type == "object") and (.value.tactics != null)
           then .value.tactics.info = [] else . end)
         | .items.goals = {}' "$f" > "$tmp"
  # Carry the original timestamp across: these filters rewrite the file on
  # every run, and a bumped mtime would make the JSON permanently look newer
  # than the module it was rendered from, disabling the staleness check below.
  touch -r "$f" "$tmp"
  mv "$tmp" "$f"
}

# Drop the stray `/--` that leads a doc comment on an anonymous command.
#
# The renderer strips a doc comment's delimiters by hand:
#
#     text.dropPrefix "/-- " |>.dropSuffix " -/" |>.dropSuffix "\n-/" ...
#
# The closing delimiter is matched three ways, the opening one only with a
# trailing *space*. This development writes its `#guard_msgs` expectations in
# the form `#guard_msgs` itself suggests — `/--` alone on a line, the message
# below it — so the suffix is removed and the prefix is not, and the page
# shows a `/--` with no closing partner. 41 of them, and they are the axiom
# and `#veil_status` pins, which is the worst place for a stray delimiter.
#
# In the JSON the leftover is its own inline: `{"normal": "/--"}` followed by
# a `softbr`, at the head of the first paragraph. Both are dropped, and only
# in that exact position, so nothing that merely begins with those characters
# is touched. The real fix is one line upstream, in `parseDocComment`.
fix_docstring_markers() {
  local f="$1" tmp="$1.tmp"
  jq -c '.items.items |= map(
           .code |= map(
             if (.markdown? != null) and (.markdown[2].blocks[0].p[0].normal? == "/--")
             then .markdown[2].blocks[0].p |=
                    (if (.[1].softbr? != null) then .[2:] else .[1:] end)
             else . end))' "$f" > "$tmp"
  touch -r "$f" "$tmp"
  mv "$tmp" "$f"
}

echo "=== 2/5  rendering each module"
# `verso-literate` re-elaborates a module from source — it needs the info
# trees, which the `.olean` does not carry — and writes its highlighted form
# as JSON.
#
# `VEIL_NO_VERIFY=1` is not optional here. The renderer runs with none of the
# native plugins (cvc5, lean-smt, lean-auto, Qq) that lake passes when it
# builds a module itself, so a module that reaches a solver call dies with
# "Could not find native implementation of external declaration
# 'cvc5.TermManager.new'" — SIGABRT, no Lean diagnostic. Skipping the check
# commands is right for a documentation pass in any case: verification is
# `verify`'s job and stage 0 insists it has already happened.
#
# It is also what keeps the renderer *terminating*. `#gen_spec` starts Veil's
# VC-manager loop, which never ends; `lean` exits the process outright and so
# never notices, but a program that returns from `main` joins every worker
# thread and waits on it forever. The pinned fork does not start that loop
# under `veil.noVerify` (`docs/Dependencies.md` §6), which is what makes the
# plain foreground run below possible — and `lake query :literateHtml`, the
# documented one-liner, work too.
#
# This still drives Verso's binaries rather than that one-liner, for one
# reason: the `jq` pass above has to run between the two stages, and the
# facet does both in one job. Everything else is Verso's — the planner above
# and the renderer below are its executables, and `literate.toml` governs
# both. Serial by choice: `Cadence.Chorus` alone peaks near 10 GB.
complete_json() { [ -s "$1" ] && jq -e . "$1" > /dev/null 2>&1; }

# A rendered module is reused when its JSON still parses, which makes a
# re-run after a failure cheap. That test says nothing about *what* produced
# the file, though, so a newer renderer would otherwise be ignored for every
# module rendered before it — the table flag landed that way once, visible on
# one page and stale on the rest. Tie the cache to the binary: if it is newer
# than the JSON, re-render.
if [ -n "$(find "$WORK/json" -name '*.json' ! -newer "$VBIN/verso-literate" -print -quit 2>/dev/null)" ]; then
  echo "    (renderer is newer than the cached JSON — re-rendering all modules)"
  rm -rf "$WORK/json"
fi

: > "$WORK/map.txt"
while IFS= read -r m; do
  [ -n "$m" ] || continue
  json="$WORK/json/${m//.//}.json"
  src="${m//.//}.lean"
  mkdir -p "$(dirname "$json")"
  # Re-render when the module's own source is newer than its JSON, as well as
  # when there is no usable JSON at all. Without this the cache answers only
  # "does a rendering exist", not "does it match the file" — editing a module
  # header then left the site showing the previous text, which is the failure
  # this check exists to prevent (the renderer-timestamp check above is the
  # same idea for the other input).
  if ! complete_json "$json" || [ "$src" -nt "$json" ]; then
    rm -f "$json"
    printf '    %-42s ' "$m"
    start=$(date +%s)
    if ! VEIL_NO_VERIFY=1 lake -Kenv=dev env "$VBIN/verso-literate" "$m" "$json" \
         > "$WORK/render.log" 2>&1 < /dev/null; then
      echo "FAILED"
      sed -n '1,10p' "$WORK/render.log" >&2
      exit 1
    fi
    # Judge by the artefact as well as the exit code: the renderer reports a
    # parse or elaboration failure in its output rather than always in its
    # status.
    if ! complete_json "$json"; then
      echo "FAILED (no parseable output)"
      sed -n '1,10p' "$WORK/render.log" >&2
      exit 1
    fi
    printf 'ok  %3ds\n' "$(( $(date +%s) - start ))"
  fi
  # Outside the branch above, so that a cached module is treated too: both
  # filters are idempotent, and running them only on a fresh render would
  # leave an edited filter unapplied to everything already on disk — the same
  # staleness the renderer check above exists to prevent.
  strip_proof_states "$json"
  fix_docstring_markers "$json"
  printf '%s\t%s\t%s\n' "$m" "$REPO/$json" "$REPO" >> "$WORK/map.txt"
done < "$WORK/plan.txt"

echo "=== 3/5  assembling the site"
rm -rf "$OUT"
mkdir -p "$OUT"
lake -Kenv=dev env "$VBIN/verso-literate-html" "$OUT/sources" "$WORK/map.txt" literate.toml
if [ ! -s "$OUT/sources/index.html" ]; then
  echo "error: the literate renderer produced no index page" >&2
  exit 1
fi

echo "=== 4/5  deriving the trust boundary from the compiled environment"
# scratch.sh supplies the native plugins Lean needs for this project's modules.
bash scripts/scratch.sh scripts/TrustSurface.lean \
  | sed -n '/^<!DOCTYPE html>/,$p' > "$OUT/trust-boundary.html"
if [ ! -s "$OUT/trust-boundary.html" ]; then
  echo "error: TrustSurface.lean produced no page" >&2
  exit 1
fi
# A drifted axiom pin must fail the docs build, not be published quietly.
if grep -q 'UNEXPECTED' "$OUT/trust-boundary.html"; then
  echo "error: an end result carries an unexpected axiom - see trust-boundary.html" >&2
  exit 1
fi

echo "=== 5/5  writing the landing page"
cat > "$OUT/index.html" <<'LANDING'
<!DOCTYPE html><html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Cadence — auditing the formalization</title>
<style>
  :root{color-scheme:light dark}
  body{max-width:62rem;margin:0 auto;padding:2rem 1.25rem;line-height:1.55;
       font-family:system-ui,-apple-system,"Segoe UI",sans-serif}
  .q{margin:1.6rem 0;padding:1rem 1.2rem;border-left:3px solid #8886}
  .q h2{margin:.1rem 0 .5rem;font-size:1.15rem}
  code{font-size:.92em}
  ul{margin:.4rem 0}
  .note{opacity:.8;font-size:.94em}
</style></head><body>

<h1>Cadence — auditing the formalization</h1>

<p>This site renders the Lean sources of the machine-checked verification of
the Cadence BFT consensus protocol, together with a trust boundary derived
from the compiled development. It is written for a reviewer who wants to
check that the formalization says what the protocol says, and that what it
claims is actually proven.</p>

<p class="note">You do not need to read any proof. A theorem holds when Lean's
kernel accepts it, relative to the axioms it uses — so the audit surface is
the <em>statements</em>, the <em>model</em> they are about, and the
<em>axioms</em> they rest on. The three questions below are exactly those.</p>

<div class="q">
<h2>1. Is this the right protocol?</h2>
<p>Read the models. Each carries a header stating its scope, the abstractions
it takes deliberately, and how each of the paper's properties is covered.</p>
<ul>
  <li><a href="sources/Cadence/Chorus/">Chorus</a> — per-slot consensus (the largest model)</li>
  <li><a href="sources/Cadence/Mvba/">Mvba</a> — the leader-based MVBA instantiation</li>
  <li><a href="sources/Cadence/Conductor/">Conductor</a> — the window-based orchestrator</li>
  <li><a href="sources/Cadence/Cadence/">Cadence</a> — the pipelining glue</li>
  <li><a href="sources/Cadence/FallbackReceipt/">FallbackReceipt</a> — the fallback receipt/propose layer</li>
</ul>
</div>

<div class="q">
<h2>2. Are these the right properties?</h2>
<p>The paper's module specifications are stated as Lean type classes, and each
implementation is checked against them.</p>
<ul>
  <li><a href="sources/Cadence/Interfaces/">Interfaces</a> — every property of every paper module, as a class field</li>
  <li><a href="sources/">The audit root</a> — every end result on one page, with its axiom pin</li>
</ul>
</div>

<div class="q">
<h2>3. Is it actually proven?</h2>
<p><a href="trust-boundary.html"><strong>The trust boundary</strong></a> —
generated from the compiled development, not written by hand: the axiom
footprint of every end result, the axioms this development declares (none),
which module contracts have no instance, and what no machine checks.</p>
</div>

<p class="note">Design rationale, the meta-assumption inventory and the paper
correspondence live in the repository's <code>docs/</code> directory; this
site renders the sources. Every module page has a search box.</p>

</body></html>
LANDING

echo
echo "=== site staged in $OUT ($(du -sh "$OUT" | cut -f1))"
echo "    python3 -m http.server -d $OUT"
