#!/usr/bin/env bash
# Check every paper citation against the label map docs/paper-labels.tsv.
#
#   scripts/paper-cites.sh [FILE...]     (default: every tracked .lean and .md file)
#
# A citation names a LaTeX label of the target revision. It is written as
# what a reader sees in the rendered PDF, with the label in parentheses as
# the secondary key, and the supplement named where it is the supplement:
#
#   Lemma 9 (`lemma:chorus-agreement`)
#   Algorithm 5, line 7 (`line:fb-pathvote-guard`)
#   Supplement, Lemma 13 (`lem:decision-propagation`)
#   Algorithm 5, lines 38–39 (`line:fb-commit-foreach`–`line:fb-commit-wait`)
#
# The check fails when a cited label is not in the map, or when the
# reference in front of it is not the map's. Only prose is read: Lean
# comments, and Markdown outside fenced code. The map is regenerated by
# scripts/paper-labels.sh.
#
# POSIX tools only (sh, awk, find, sed, sort), so that it runs wherever the
# docs build does (scripts/docs.sh calls it beside the link resolution).
set -eu
root="$(cd "$(dirname "$0")/.." && pwd)"
cd "$root"
if [ "$#" -eq 0 ]; then
  # Outside a git checkout (the docs container), every source file instead.
  files="$(git ls-files '*.lean' '*.md' 2>/dev/null || true)"
  [ -n "$files" ] || files="$(find . \( -name .lake -o -name .git -o -name node_modules \) -prune -o \
    \( -name '*.lean' -o -name '*.md' \) -type f -print | sed 's|^\./||' | LC_ALL=C sort)"
  [ -n "$files" ] || { echo "paper-cites: no source files found" >&2; exit 1; }
  set -- $files
fi

# Byte semantics everywhere, so every awk agrees on positions and lengths.
LC_ALL=C exec awk -F '\t' '
function ref(l) { return (DOC[l] == "supplement" ? "Supplement, " : "") REF[l] }
function endswith(s, t) { return length(s) >= length(t) && substr(s, length(s) - length(t) + 1) == t }
function flat(s) {
  # A wrapped citation: drop the line break, its indentation and a `--`.
  gsub(/[ \t\r]*\n[ \t\r\n]*(--[ \t\r]*)?/, " ", s)
  return s
}
# Expected references for a citation `a` or a range `a`–`b`, into EXP[1..].
function expected(a, b,    n, pa, pb, alga, algb, la, lb) {
  n = 0
  if (b == "") { EXP[++n] = ref(a); return n }
  pa = index(REF[a], ", line "); pb = index(REF[b], ", line ")
  if (REF[a] ~ /^Algorithm [^ ]+, line [^ ]+$/ && REF[b] ~ /^Algorithm [^ ]+, line [^ ]+$/) {
    alga = substr(REF[a], 1, pa - 1); algb = substr(REF[b], 1, pb - 1)
    la = substr(REF[a], pa + 7); lb = substr(REF[b], pb + 7)
    if (alga == algb && DOC[a] == DOC[b])
      EXP[++n] = (DOC[a] == "supplement" ? "Supplement, " : "") alga ", lines " la "–" lb
  }
  if (ref(a) == ref(b)) EXP[++n] = ref(a)
  return n
}
function lineof(seg, segline, k,    t) { t = substr(seg, 1, k - 1); return segline + gsub(/\n/, "", t) }
function emit(text, line) { NSEG++; SEG[NSEG] = text; SEGL[NSEG] = line }

# Prose spans of a Lean file: block comments (nested) and line comments,
# skipping string literals.
function lean_segments(    ln, s, len, i, rest, p1, p2, p3, best, which, depth, instr, cur, curline) {
  depth = 0; instr = 0
  for (ln = 1; ln <= NL; ln++) {
    s = LINE[ln]; len = length(s); i = 1
    if (depth > 0) cur = cur "\n"
    while (i <= len) {
      rest = substr(s, i)
      if (instr) {
        p1 = index(rest, "\\"); p2 = index(rest, "\"")
        if (p1 && (!p2 || p1 < p2)) { i += p1 + 1; continue }
        if (p2) { instr = 0; i += p2; continue }
        i = len + 1; continue
      }
      if (depth > 0) {
        p1 = index(rest, "/-"); p2 = index(rest, "-/")
        if (p1 && (!p2 || p1 < p2)) { depth++; cur = cur substr(rest, 1, p1 + 1); i += p1 + 1; continue }
        if (p2) {
          depth--; cur = cur substr(rest, 1, p2 + 1); i += p2 + 1
          if (depth == 0) emit(cur, curline)
          continue
        }
        cur = cur rest; i = len + 1; continue
      }
      p1 = index(rest, "/-"); p2 = index(rest, "--"); p3 = index(rest, "\"")
      best = 0; which = ""
      if (p1 && (!best || p1 < best)) { best = p1; which = "block" }
      if (p2 && (!best || p2 < best)) { best = p2; which = "line" }
      if (p3 && (!best || p3 < best)) { best = p3; which = "string" }
      if (which == "") { i = len + 1; continue }
      if (which == "block") { depth = 1; cur = "/-"; curline = ln; i += best + 1; continue }
      if (which == "line") { emit(substr(rest, best), ln); i = len + 1; continue }
      instr = 1; i += best
    }
  }
  if (depth > 0) emit(cur, curline)
}

# Prose spans of a Markdown file: everything outside fenced code.
function md_segments(    ln, f, j, cl, cur, curline) {
  cur = ""; curline = 1
  for (ln = 1; ln <= NL; ln++) {
    f = substr(LINE[ln], 1, 3)
    if (f == "```" || f == "~~~") {
      cl = 0
      for (j = ln + 1; j <= NL; j++) if (substr(LINE[j], 1, 3) == f) { cl = j; break }
      if (cl) {
        emit(cur, curline); cur = ""; curline = cl; ln = cl
        continue
      }
    }
    cur = (cur == "" && ln == curline ? LINE[ln] : cur "\n" LINE[ln])
  }
  emit(cur, curline)
}

function check(file, seg, segline,    pos, st, en, m, inner, sep, a, b, bst, n, k, ok, before, after, want, lab, lc, rc, len) {
  split("", GROUPED)
  pos = 1
  while (match(substr(seg, pos), GRE)) {
    st = pos + RSTART - 1; en = st + RLENGTH; pos = en
    m = substr(seg, st, RLENGTH); inner = substr(m, 2, RLENGTH - 2)
    sep = index(inner, "`–`")
    if (sep) { a = substr(inner, 1, sep - 1); b = substr(inner, sep + length("`–`")); bst = st + 1 + length(a) + length("`–`") }
    else { a = inner; b = ""; bst = 0 }
    GROUPED[st + 1] = 1; if (bst) GROUPED[bst] = 1
    if ((a in NAT) || (b != "" && (b in NAT))) continue
    if (!(a in REF) || (b != "" && !(b in REF))) {
      ERR[++NERR] = file ":" lineof(seg, segline, st) ": `" ((a in REF) ? b : a) "` is not a label of the target"
      continue
    }
    CITES++
    if (file in DEFERRED) continue
    k = st - 120; if (k < 1) k = 1
    before = flat(substr(seg, k, st - k)); after = substr(seg, en, 1)
    n = expected(a, b); ok = 0
    if (after == ")") for (k = 1; k <= n; k++) if (endswith(before, EXP[k] " (")) ok = 1
    if (!ok) {
      want = n ? EXP[1] : ref(a)
      ERR[++NERR] = file ":" lineof(seg, segline, st) ": `" a "`" (b != "" ? "–`" b "`" : "") " should read \"" want " (`…`)\""
    }
  }
  pos = 1
  while (match(substr(seg, pos), TRE)) {
    st = pos + RSTART - 1; len = RLENGTH; lab = substr(seg, st, len)
    lc = (st > 1 ? substr(seg, st - 1, 1) : ""); rc = substr(seg, st + len, 1)
    if ((lc != "" && lc ~ /[A-Za-z0-9_:.\/$-]/) || (rc != "" && rc ~ /[A-Za-z0-9_*]/)) { pos = st + 1; continue }
    pos = st + len
    if ((st in GROUPED) || (lab in NAT) || !(lab in REF)) continue
    ERR[++NERR] = file ":" lineof(seg, segline, st) ": `" lab "` is cited without backticks"
  }
}

function process(file,    k) {
  if (file == "" || (file in RECORDS)) return
  NSEG = 0
  if (file ~ /\.lean$/) lean_segments(); else md_segments()
  for (k = 1; k <= NSEG; k++) check(file, SEG[k], SEGL[k])
}

BEGIN {
  # Frozen records: they cite the paper as it was when they were written.
  RECORDS["docs/History.md"]; RECORDS["docs/AuditReport.md"]
  # Files whose citations keep the bare-label form until the session that
  # edits them anyway (docs/PaperAlignment.md §8, R15). Their labels must
  # still be in the map.
  DEFERRED["Cadence/Interfaces.lean"]; DEFERRED["Cadence/System.lean"]
  # Labels that are cited on purpose although the target does not have them.
  NAT["line:da-rebroadcast"]       # a v1 rule, removed in v2; cited as removed
  NAT["line:mvba:td-decide"]       # removed from the supplement at eb1bb51
  NAT["line:mvba:hp-pool"]         # removed from the supplement at eb1bb51
  NAT["line:mvba:tfp-commit"]      # removed from the supplement at eb1bb51
  NAT["eq:predecessor-deadline"]   # folded into eq:slot-deadline at the target
  NAT["lem:certified-prefix"]      # unlabelled at the target
  MAPFILE = ARGV[1]; NMAP = 0; NERR = 0; CITES = 0; CURFILE = ""
}
FILENAME == MAPFILE {
  if ($0 ~ /^#/ || NF < 3) next
  if (!($1 in REF)) NMAP++
  REF[$1] = $3; DOC[$1] = $2
  p = $1; sub(/:.*/, "", p)
  if (!(p in PFX)) { PFX[p]; PFXRE = PFXRE (PFXRE == "" ? "" : "|") p }
  next
}
FNR == 1 {
  if (GRE == "") {
    LAB = "(" PFXRE "):[A-Za-z0-9_:.-]*[A-Za-z0-9_]"
    GRE = "`" LAB "`(–`" LAB "`)?"
    TRE = LAB
  }
  process(CURFILE); CURFILE = FILENAME; NL = 0
}
{ LINE[++NL] = $0 }
END {
  process(CURFILE)
  for (k = 1; k <= NERR; k++) print ERR[k]
  printf "paper-cites: %d citations checked, %d problem(s), map of %d labels\n", CITES, NERR, NMAP
  exit (NERR ? 1 : 0)
}
' docs/paper-labels.tsv "$@"
