#!/usr/bin/env bash
# Check every paper citation against the label map docs/paper-labels.tsv.
#
#   scripts/paper-cites.sh [FILE...]     (default: every tracked .lean and .md file)
#
# A citation names a LaTeX label of the target revision. It is written as
# what a reader sees in the rendered PDF, with the label in parentheses as
# the secondary key, and the supplement named where it is the supplement:
#
#   Lemma 9 (`lemma:chorus-agreement`)
#   Algorithm 5, line 7 (`line:fb-pathvote-guard`)
#   Supplement, Lemma 13 (`lem:decision-propagation`)
#   Algorithm 5, lines 38–39 (`line:fb-commit-foreach`–`line:fb-commit-wait`)
#
# The check fails when a cited label is not in the map, or when the
# reference in front of it is not the map's. Only prose is read: Lean
# comments, and Markdown outside fenced code. The map is regenerated by
# scripts/paper-labels.sh.
set -euo pipefail
root="$(cd "$(dirname "$0")/.." && pwd)"
cd "$root"
if [ "$#" -eq 0 ]; then
  set -- $(git ls-files '*.lean' '*.md')
fi
exec python3 - "$@" <<'EOF'
import re, sys

MAP = {}
for l in open('docs/paper-labels.tsv'):
    if l.startswith('#'):
        continue
    lab, doc, ref, page = l.rstrip('\n').split('\t')
    MAP[lab] = (doc, ref)

# Frozen records: they cite the paper as it was when they were written.
RECORDS = {'docs/History.md', 'docs/AuditReport.md'}
# Files whose citations keep the bare-label form until the session that
# edits them anyway (docs/PaperAlignment.md §8, R15). Their labels must
# still be in the map.
DEFERRED = {'Cadence/Interfaces.lean', 'Cadence/System.lean'}
# Labels that are cited on purpose although the target does not have them.
NOT_AT_TARGET = {
    'line:da-rebroadcast': 'a v1 rule, removed in v2; cited as removed',
    'line:mvba:td-decide': 'removed from the supplement at eb1bb51; cited as removed',
    'line:mvba:hp-pool': 'removed from the supplement at eb1bb51; cited as removed',
    'line:mvba:tfp-commit': 'removed from the supplement at eb1bb51; cited as removed',
    'eq:predecessor-deadline': 'folded into eq:slot-deadline at the target; cited as folded',
    'lem:certified-prefix': 'unlabelled at the target; cited as unlabelled',
}

PREFIXES = sorted({k.split(':')[0] for k in MAP}, key=len, reverse=True)
LAB = r'(?:%s):[A-Za-z0-9_:.\-]*[A-Za-z0-9_]' % '|'.join(map(re.escape, PREFIXES))
TOKEN = re.compile(r'(?<![\w:./$-])(' + LAB + r')(?![\w*])')
GROUP = re.compile(r'`(' + LAB + r')`(?:–`(' + LAB + r')`)?')


def ref(lab):
    doc, r = MAP[lab]
    return ('Supplement, ' + r) if doc == 'supplement' else r


def expected(a, b):
    if not b:
        return [ref(a)]
    out = []
    ma = re.match(r'(Algorithm \S+), line (\S+)$', MAP[a][1])
    mb = re.match(r'(Algorithm \S+), line (\S+)$', MAP[b][1])
    if ma and mb and ma.group(1) == mb.group(1) and MAP[a][0] == MAP[b][0]:
        sup = 'Supplement, ' if MAP[a][0] == 'supplement' else ''
        out.append(f'{sup}{ma.group(1)}, lines {ma.group(2)}–{mb.group(2)}')
    if ref(a) == ref(b):
        out.append(ref(a))
    return out


def prose(text, lean):
    """Spans of prose: Lean comments, or Markdown outside fenced code."""
    if not lean:
        pos = 0
        for m in re.finditer(r'^(```|~~~).*?^\1[^\n]*$', text, re.S | re.M):
            yield pos, m.start()
            pos = m.end()
        yield pos, len(text)
        return
    i, n = 0, len(text)
    while i < n:
        if text.startswith('/-', i):
            depth, j = 1, i + 2
            while j < n and depth:
                if text.startswith('/-', j):
                    depth += 1; j += 2
                elif text.startswith('-/', j):
                    depth -= 1; j += 2
                else:
                    j += 1
            yield i, j
            i = j
        elif text.startswith('--', i):
            j = text.find('\n', i)
            j = n if j < 0 else j
            yield i, j
            i = j
        elif text[i] == '"':
            j = i + 1
            while j < n and text[j] != '"':
                j += 2 if text[j] == '\\' else 1
            i = j + 1
        else:
            i += 1


def flat(s):
    # A wrapped citation: drop the line break, its indentation and a `--`.
    return re.sub(r'\s*\n\s*(?:--\s*)?', ' ', s)


errors, cites = [], 0
for f in sys.argv[1:]:
    if f in RECORDS or f.endswith('paper-labels.tsv'):
        continue
    try:
        text = open(f).read()
    except (OSError, UnicodeDecodeError):
        continue
    lean = f.endswith('.lean')
    for s, e in prose(text, lean):
        seg = text[s:e]
        line = lambda k: text.count('\n', 0, s + k) + 1
        grouped = set()
        for m in GROUP.finditer(seg):
            a, b = m.group(1), m.group(2)
            grouped.update({m.start(1), m.start(2) if b else -1})
            labs = [x for x in (a, b) if x]
            if any(x in NOT_AT_TARGET for x in labs):
                continue
            missing = [x for x in labs if x not in MAP]
            if missing:
                errors.append(f'{f}:{line(m.start())}: `{missing[0]}` is not a label of the target')
                continue
            cites += 1
            if f in DEFERRED:
                continue
            before = flat(seg[max(0, m.start() - 120):m.start()])
            after = seg[m.end():m.end() + 1]
            ok = after == ')' and any(before.endswith(r + ' (') for r in expected(a, b))
            if not ok:
                want = expected(a, b)[0] if expected(a, b) else ref(a)
                errors.append(f'{f}:{line(m.start())}: `{a}`{"–`" + b + "`" if b else ""}'
                              f' should read "{want} (`…`)"')
        for m in TOKEN.finditer(seg):
            lab = m.group(1)
            if m.start(1) in grouped or lab in NOT_AT_TARGET:
                continue
            if lab not in MAP:
                continue  # not backticked and not a label: prose such as `prop:` in a word
            errors.append(f'{f}:{line(m.start())}: `{lab}` is cited without backticks')

for e in errors:
    print(e)
print(f'paper-cites: {cites} citations checked, {len(errors)} problem(s), '
      f'map of {len(MAP)} labels')
sys.exit(1 if errors else 0)
EOF
